// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5SuGoSabVnXLEk1spy_3v6o28Sx_1i8k',
    appId: '1:927952381345:android:5bb7cfa16e01c0d0e3d7e0',
    messagingSenderId: '927952381345',
    projectId: 'flutter-chat-7b08e',
    storageBucket: 'flutter-chat-7b08e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUq2UtiDVY7Ru2xzBPw9E0um3cGnLcbwE',
    appId: '1:927952381345:ios:e7a4cf5814134fa1e3d7e0',
    messagingSenderId: '927952381345',
    projectId: 'flutter-chat-7b08e',
    storageBucket: 'flutter-chat-7b08e.appspot.com',
    iosClientId: '927952381345-i9bpl3rk3p1bs08f5gft36rf9qvsvn5i.apps.googleusercontent.com',
    iosBundleId: 'com.agdev.chatapp',
  );
}
